version: '3.1'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: releave
    volumes:
      - /home/almirjr94/Documents/dev/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8181:80"
    restart: always
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

