spring:
  profiles:
    active: dev
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
     hikari:
       minimum-idle: 1
       maximum-pool-size: 9
